# Generated by Django 5.2.5 on 2025-08-13 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0006_alter_offerdetail_offer'),
        ('orders_app', '0002_order_created_at_order_delivery_time_in_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='offer_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='offers_app.offerdetail'),
        ),
    ]
