# Generated by Django 5.2.5 on 2025-08-12 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='account_type',
            new_name='type',
        ),
    ]
