# Generated by Django 5.2.5 on 2025-08-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('revisions', models.IntegerField()),
                ('price', models.IntegerField()),
                ('features', models.CharField(max_length=255)),
                ('offer_type', models.CharField(max_length=255)),
            ],
        ),
    ]
