# Generated by Django 5.2.5 on 2025-08-12 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0002_remove_offer_features_remove_offer_offer_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offerdetail',
            old_name='delivery_time',
            new_name='delivery_time_in_days',
        ),
    ]
