# Generated by Django 5.2.5 on 2025-08-12 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0003_rename_delivery_time_offerdetail_delivery_time_in_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerdetail',
            name='features',
            field=models.JSONField(),
        ),
    ]
