# Generated by Django 5.2.5 on 2025-08-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_app', '0002_remove_review_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
